edition = "2024"
style_edition = "2024"
max_width = 100
unstable_features = true
imports_granularity = "Crate"
reorder_impl_items = true
use_field_init_shorthand = true
format_code_in_doc_comments = true
wrap_comments = true
